#Part:1 - Arrays
As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array(NumPy is used for working with arrays)
#NumPY stands for? Ans: Numerical Python
#Numpy developed by? Ans: Travis Oliphant

# ***Numpy Arrays***
arange(), linspace(), zeros(), ones(), eye(), rand(), randn(), randint()
#Methods:
 reshape(), max(), min(), argmax(), argmin()
Attributes: size, shape, dtype
#Indexing & slicing of 1-D arrays (vectors)
#Indexing & slicing 2-D arrays (matrices)


In [1]:
# Let import NumPy
import numpy as np

# **Numpy Arrays**
**Vectors**: Vectors are strictly 1-dimensional array.

**Matrices**: Matrices are 2-dimensional (matrix can still have only one row or one column).

# Creating NumPy Arrays


## From Python data type (e.g. List, Tuple)

In [3]:
#Lets create a python list.
my_list =[-1,0,1]
my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function.
The NumPy's array function can be accessed by typing "np.array".
We need to cast our Python data structure, my_list, as a parameter to the array function.

In [8]:
my_array = np.array(my_list)
my_array


array([-1,  0,  1])

In [9]:
type(my_array) # type function used to find parameter type.

numpy.ndarray

In [21]:
np.ndim(my_array) #check dimension using ndim

1

Matrices  

In [11]:
#Lets create and cast a list of list to generate 2-D array
my_matrix =[[1,2,3],[4,5,6],[7,8,9],[4,5,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [23]:
type(my_matrix)


list

In [15]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [16]:
type(matrix_one)

numpy.ndarray

In [19]:
np.ndim(matrix_one) #check dimension using ndim

2

# Tuple

In [24]:
#we can use Tuple instead of list as well.
my_tuple =(-1,0,1)
my_tuple

(-1, 0, 1)

In [25]:
type(my_tuple) #check type

tuple

In [28]:
#convert tuple as a array
my_array = np.array(my_tuple)
my_array ,type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

## Array creation using NumPy's Built-in methods

# arange()
 * arange() is very much similar to Python function range()

 *   Syntax: arange([start,] stop[,
  step,], dtype=None)
 *   Return evenly spaced values within a given interval.




